### ISSUE TITLE
page title, Session Code, author picture is too big.

### ISSUE THREAD

**Issue by jyheo** [cloudhubs/acmsac#16]
Thanks for your hard working on this wonderful online conference site!

Some minors I'd like to comment.
- Page title is "React App".. I think it needs to be changed to "ACM SAC 2020 online .. something."
- The "Session Code" is displaying the session chair?
- I think the author picture is too big. So I need to scroll a lot  to watch the presentation video.

**Comment by walker76** [comment]
Thank you for the feedback. We should have a fix for these issues going out shortly! Let us know if you find anything else.
